### ISSUE TITLE
Make the default aspect "Perfective"

### ISSUE THREAD

**Issue by beechnut** [rossmeissl/verbs#15]
``` ruby
> Verbs::Conjugator.conjugate :eat, tense: :past
 => "usually eaten"
```

If I am looking for the past tense of "eat", I want to be given "ate".

The habitual aspect is an unexpected default and far less common in English than the perfective. Common cases and expectations should comprise the defaults.

**Comment by rossmeissl** [comment]
@beechnut any plans to tackle this?

**Comment by rossmeissl** [comment]
@beechnut still interested in making a PR for this?
