### ISSUE TITLE
"present perfective" and "future perfective" examples are impossible English

### ISSUE THREAD

**Issue by jeidsath** [rossmeissl/verbs#20]
"I am having accepted" and "I will be having accepted" can never occur in English.  The perfect would be used for both.  "I have accepted" or "I will have accepted."

**Comment by jeidsath** [comment]
PR: https://github.com/rossmeissl/verbs/pull/23

**Comment by rossmeissl** [comment]
@jeidsath what about a "Having accepted, . . ." clause?

**Comment by rossmeissl** [comment]
@jeidsath I'm closing this for now due to non-response but feel free to reopen!
