### ISSUE TITLE
No options for passive voice

### ISSUE THREAD

**Issue by jeidsath** [rossmeissl/verbs#21]
Would you accept a PR that adds the passive voice?  I see a stub for it here:

https://github.com/rossmeissl/verbs/blob/master/lib/verbs/conjugator.rb#L43

**Comment by rossmeissl** [comment]
Hi @jeidsath, I wll be having accepted one with pleasure!

**Comment by jeidsath** [comment]
PR: https://github.com/rossmeissl/verbs/pull/27

**Comment by rossmeissl** [comment]
Continuing conversation in #27
