### ISSUE TITLE
rubygems not up to date with github version

### ISSUE THREAD

**Issue by bendelonlee** [rossmeissl/verbs#32]
Thanks for making this gem!

I noticed that the version you have on rubygems doesn't seem to have all fixes that are on github. 

I installed your gem this morning, here's a piece of an interaction pattern:
![image](https://user-images.githubusercontent.com/41645771/50548365-7a249400-0c08-11e9-91d5-baa2283aa570.png)

**Comment by searls** [comment]
Apologies for the bump, but the RG.o version hasn't been pushed in over 6 years now. Any chance you'd be willing to cut a release?

**Comment by rossmeissl** [comment]
@searls @bendelonlee sorry for the ridiculous delay. This has been bumped and published.
